name: Send Views Tweets

# Controls when the workflow will run
on:
  schedule: # “At 17:00 on every day-of-week from Monday through Thursday.”
    # - cron: "0 17 * * 1-4"
    - cron: "*/5 * * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
      #- name: tweet
        #uses: Satak/webrequest-action@v1.2.3
        #with:
          # Web request URL endpoint
          #url: "https://takeawaybooks.com/api/twitter"
          #method: GET
          # headers: '{"api-key": "${{ secrets.API_KEY }}"}'