name: Social

# Controls when the workflow will run
on:
  schedule:
   - cron: "30 8 * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: tweet
        uses: Satak/webrequest-action@v1.2.3
        with:
          # Web request URL endpoint
          url: "https://barefootrecipe.com/api/social"
          method: GET
